### ISSUE TITLE
postgrest dies with 137 in m1

### ISSUE THREAD

**Issue by yrimal** [medic/cht-sync#6]
>pipeline-postgrest-1 exited with code 137

Related issues:
[https://github.com/supabase/cli/issues/33](https://github.com/supabase/cli/issues/33)
Probable solution: [here](https://github.com/PostgREST/postgrest/issues/1785#issuecomment-832884561)

**Comment by yrimal** [comment]
Here's updated docker-compose.yml that I'm using: 
```
version: '3.7'

services:
  logstash:
    image: medicmobile/cht-logstash-couchdb:latest
    build: ./logstash/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DB=${COUCHDB_DB}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_SEQ=/tmp/couchdb/sequence_path.txt
      - COUCHDB_SECURE=${COUCHDB_SECURE:-true}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_HOST=host.docker.internal
      - HTTP_ENDPOINT=postgrest:3000

  postgrest:
    image: postgrest/postgrest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
```
Everything below it is same.
