### ISSUE TITLE
Create Postgres instance using EKS

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-sync#87]
Create a postgres instance for use with the BRAC work as suggested [here](https://github.com/medic/medic-infrastructure/issues/934#issuecomment-2056765930). The current RDS instance is full and requires the support of the infra team to debug and get logs.

**Comment by witash** [comment]
@Hareet there's a draft helm chart for cht-sync [here](https://github.com/medic/cht-sync/pull/90) which includes a postgres instance. But how can we allow access to it? I was using port forwarding locally but do not have permissions to on EKS, and anyway will not work for dashboards externally

**Comment by witash** [comment]
> @Hareet there's a draft helm chart for cht-sync [here](https://github.com/medic/cht-sync/pull/90) which includes a postgres instance. But how can we allow access to it? I was using port forwarding locally but do not have permissions to on EKS, and anyway will not work for dashboards externally

I see EKS will create an internet facing ELB if you request a LoadBalancer service, but its not accepting TCP connections

```
apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector: 
    inner.service: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port | default "5432" }}
      targetPort: 5432
```
